### ISSUE TITLE
Proceeding to checkout gives 500 [GET] /cart/c/c1-abcd?key=1234 status=500

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1308]
```
[GET] /cart/c/c1-d22d6732a08c2dfb337d1dbfbfc01e9b?key=ddf427ea328138a27e121d517a7144c5 status=500
```

```
⨯ Error: Cannot find module '/var/task/.next/server/app/page.js'
Require stack:
- /var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/___next_launcher.cjs
- /var/task/___vc/__launcher/chunk-N3ULQXIM.js
- /var/task/___vc/__launcher/chunk-5UAC7W5H.js
- /var/task/___vc/__launcher/__launcher.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at /var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25516
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at exports.b (/var/task/___vc/__launcher/chunk-5UAC7W5H.js:1:1033)
    at /var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1809)
    at e.<computed>.L._load (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1413)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at w.require (/var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25732)
    at require (node:internal/modules/helpers:177:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
    '/var/task/___next_launcher.cjs',
    '/var/task/___vc/__launcher/chunk-N3ULQXIM.js',
    '/var/task/___vc/__launcher/chunk-5UAC7W5H.js',
    '/var/task/___vc/__launcher/__launcher.js'
  ],
  page: '/'
}
```

```
Error: Cannot find module '/var/task/.next/server/app/page.js'
Require stack:
- /var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/___next_launcher.cjs
- /var/task/___vc/__launcher/chunk-N3ULQXIM.js
- /var/task/___vc/__launcher/chunk-5UAC7W5H.js
- /var/task/___vc/__launcher/__launcher.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at /var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25516
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at exports.b (/var/task/___vc/__launcher/chunk-5UAC7W5H.js:1:1033)
    at /var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1809)
    at e.<computed>.L._load (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:1413)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at w.require (/var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25732)
    at require (node:internal/modules/helpers:177:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
    '/var/task/___next_launcher.cjs',
    '/var/task/___vc/__launcher/chunk-N3ULQXIM.js',
    '/var/task/___vc/__launcher/chunk-5UAC7W5H.js',
    '/var/task/___vc/__launcher/__launcher.js'
  ],
  page: '/'
}
```

```
Error: Runtime exited with error: exit status 1
```

![Screenshot 2024-03-12 at 15 11 03](https://github.com/vercel/commerce/assets/12736263/fad06d33-4bd0-470b-9c1f-817a9cb53a6e)

**Comment by danieldanielecki** [comment]
Project live: shop.ditectrev.com

**Comment by leerob** [comment]
It's hard to tell what this could be since its from your own forked code that is not in this template, right? We don't have a `/cart/` route included.

**Comment by danieldanielecki** [comment]
I haven't done any coding other than changing the logo, repo (sorry, I didn't link): https://github.com/Ditectrev/shop

**Comment by danieldanielecki** [comment]
Can you check https://github.com/vercel/commerce/issues/1274? Maybe some redirection misconfiguration it causing this?

**Comment by danieldanielecki** [comment]
The same problem when I've tried on the Vercel domain itself: https://shopify-ditectrev.vercel.app/cart/c/c1-152cd17be865bb952f6c2c1b20cc6afa?key=79509033b2c26ac4a6929b8c733a5b46

omg...

**Comment by danieldanielecki** [comment]
shocking, I had to set up redirect here in `Domains` to have the checkout working!!

<img width="1670" alt="Screenshot 2024-05-29 at 19 34 23" src="https://github.com/vercel/commerce/assets/12736263/e44706d2-8f99-4720-a226-ad1fb65832ce">

**Comment by danieldanielecki** [comment]
but it doesn't on primary domain...

**Comment by danieldanielecki** [comment]
This I'll close, and continue in https://github.com/vercel/commerce/issues/1341. I explained it in https://github.com/vercel/commerce/issues/1341#issuecomment-3631037834 & partially in https://github.com/vercel/commerce/issues/1341#issuecomment-3631031109 why this happens
