### ISSUE TITLE
Page not updating, nothing from shopify is being displayed.

### ISSUE THREAD

**Issue by Mbensler** [vercel/commerce#1395]
I have followed the guide and deployed the template from Vercel, and added all the correct env variables.
I have also added my domain on vercel, and set my webhooks to the domain. 

When i create products or pages or basically anything on Shopify nothing is being displayed on the domain. 
If i click preview on the product it takes me to a 404 page on my domain but with the correct product name. 
I can see that when i click the product on shopify it first shows the shopify store url and then redirects to my page.

Does anyone know what i have done wrong?

**Comment by Mbensler** [comment]
Looking at my logs in the vercel dashboard i am getting these errors:
```js
⨯ Error: {"error":{"message":"","extensions":{"code":"UNAUTHORIZED"}},"query":"\n  query getCollectionProducts(\n    $handle: String!\n    $sortKey: ProductCollectionSortKeys\n    $reverse: Boolean\n  ) {\n    collection(handle: $handle) {\n      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n        edges {\n          node {\n            ...product\n          }\n        }\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    options {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPrice {\n        amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n          title\n          availableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n    }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    height\n  }\n\n  \n  fragment seo on SEO {\n    description\n    title\n  }\n\n\n"}
    at tj (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:126:729)
    at i (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:2700)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eI (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:24574)
    at eq (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:26873)
    at eB (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:27056)
    at Immediate._onImmediate (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:14618)
    at process.processImmediate (node:internal/timers:485:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17) {
  digest: '509360563'
}
```
and 
```js
⨯ Error:⨯ Error: {"error":{"message":"","extensions":{"code":"UNAUTHORIZED"}},"query":"\n  query getProducts($sortKey: ProductSortKeys, $reverse: Boolean, $query: String) {\n    products(sortKey: $sortKey, reverse: $reverse, query: $query, first: 100) {\n      edges {\n        node {\n          ...product\n        }\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    options {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPrice {\n        amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n          title\n          availableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n    }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    height\n  }\n\n  \n  fragment seo on SEO {\n    description\n    title\n  }\n\n\n"}
    at tj (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:126:729)
    at i (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:2700)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eI (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:24574)
    at eq (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:26873)
    at eB (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:27056)
    at Immediate._onImmediate (/var/task/node_modules/.pnpm/next@15.0.0-rc.1_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__rea_sjig2s3n3wyjmhhbbzmei52ggi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:14618)
    at process.processImmediate (node:internal/timers:485:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17) {
  digest: '396217267'
}
```

**Comment by Mbensler** [comment]
So i just searched for a product i created (i tried searching earlier without luck) but this time the products actually showed up. Clicking on the product takes me to `https://mydomain.vercel.app/product/test` whereas clicking on the product on the shopify page takes me to `https://mayscorner.vercel.app/products/test` which results in a 404.

**Comment by Mbensler** [comment]
Alright products are now being displayed on the frontpage. I havent changed anything so i have no idea.
The menu and footer are however still unchanged and empty. Even when changing them on shopify.

**Comment by Mbensler** [comment]
I dont know if shopify is just very slow, or what is happening. Menu also just appeared after an hour of trying.
Apologies for all the comments and the issue.
