### ISSUE TITLE
BigCommerce call getAllProducts API facing Internal server error issue

### ISSUE THREAD

**Issue by Quynh-Nguyen** [vercel/commerce#157]
Issue: Cannot call getAllProducts API to BigCommerce GraphQL API.
Expected: Should return all of products

Tracing log:
```FetcherError: Internal server error
    at Object.fetchGraphqlApi [as fetch] (webpack-internal:///./framework/bigcommerce/api/utils/fetch-graphql-api.ts:38:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async getAllProducts (webpack-internal:///./framework/bigcommerce/api/operations/get-all-products.ts:85:7)
    at async getStaticProps (webpack-internal:///./pages/index.tsx:61:7)
    at async renderToHTML (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/render.js:28:109)
    at async /usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async __wrapper (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderToHTML (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:133:522)
    at async DevServer.renderToHTML (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:72:236)
    at async Object.fn (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:56:580)
    at async Router.execute (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/usr/local/var/www/html/DFORT/YNa/commerce/node_modules/next/dist/next-server/server/next-server.js:34:1081) {
  code: undefined,
  errors: [
    {
      message: 'Internal server error',
      path: [Array],
      locations: [Array]
    }
  ],
  status: 200
}
```

Do you guys getting the same issue?

**Comment by Quynh-Nguyen** [comment]
@lfades Can you please assist this.

**Comment by Itsaadarsh** [comment]
Hello there, @Quynh-Nguyen can you let me know how to reproduce this particular error? And then maybe I could assist you with it.

**Comment by Quynh-Nguyen** [comment]
@Itsaadarsh Hello.
It's seems fixed by the last commit.
Thank you so much for your assist.

**Comment by Itsaadarsh** [comment]
Alright.
