### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "name" argument must be of type string. Received null

### ISSUE THREAD

**Issue by lonfger** [vercel/commerce#173]
Hi,
When first running `npm run dev`, I was seeing the following error:
![image](https://user-images.githubusercontent.com/13881250/105274219-b94f2480-5bd7-11eb-8022-6e5db5f07bd3.png)

```js
TypeError [ERR_INVALID_ARG_TYPE]: The "name" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Resolver.queryA [as resolve4] (dns.js:216:5)
    at D:\demos\commerce\node_modules\@zeit\dns-cached-resolve\lib\resolve4.js:5:18
    at new Promise (<anonymous>)
    at resolve4 (D:\demos\commerce\node_modules\@zeit\dns-cached-resolve\lib\resolve4.js:4:12)
    at D:\demos\commerce\node_modules\@zeit\dns-cached-resolve\lib\dns-resolve.js:29:55
    at RetryOperation.runAttempt [as _fn] (D:\demos\commerce\node_modules\async-retry\lib\index.js:35:15)
    at Timeout._onTimeout (D:\demos\commerce\node_modules\retry\lib\retry_operation.js:81:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_INVALID_ARG_TYPE',
  url: '321',
  opts: {
    method: 'POST',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    body: '{"query":"\\n  query getAllProducts(\\n    $hasLocale: Boolean = false\\n    $locale: String = \\"null\\"\\n    $entityIds: [Int!]\\n    $first: Int = 10\\n    $products: Boolean = false\\n    $featuredProducts: Boolean = false\\n    $bestSellingProducts: Boolean = false\\n    $newestProducts: Boolean = false\\n  ) {\\n    site {\\n      products(first: $first, entityIds: $entityIds) @include(if: $products) {\\n        ...productConnnection\\n      }\\n      featuredProducts(first: $first) @include(if: $featuredProducts) {\\n        ...productConnnection\\n      }\\n      bestSellingProducts(first: $first) @include(if: $bestSellingProducts) {\\n        ...productConnnection\\n      }\\n      newestProducts(first: $first) @include(if: $newestProducts) {\\n        ...productConnnection\\n      }\\n    }\\n  }\\n\\n  \\n  fragment productConnnection on ProductConnection {\\n    pageInfo {\\n      startCursor\\n      endCursor\\n    }\\n    edges {\\n      cursor\\n      node {\\n        ...productInfo\\n      }\\n    }\\n  }\\n\\n  \\n  fragment productInfo on Product {\\n    entityId\\n    name\\n    path\\n    brand {\\n      entityId\\n    }\\n    description\\n    prices {\\n      ...productPrices\\n    }\\n    images {\\n      edges {\\n        node {\\n          urlOriginal\\n          altText\\n          isDefault\\n        }\\n      }\\n    }\\n    variants {\\n      edges {\\n        node {\\n          entityId\\n          defaultImage {\\n            urlOriginal\\n            altText\\n            isDefault\\n          }\\n        }\\n      }\\n    }\\n    productOptions {\\n      edges {\\n        node {\\n          __typename\\n          entityId\\n          displayName\\n          ...multipleChoiceOption\\n        }\\n      }\\n    }\\n    localeMeta: metafields(namespace: $locale, keys: [\\"name\\", \\"description\\"])\\n      @include(if: $hasLocale) {\\n      edges {\\n        node {\\n          key\\n          value\\n        }\\n      }\\n    }\\n  }\\n\\n  \\n  fragment 
productPrices on Prices {\\n    price {\\n      value\\n      currencyCode\\n    }\\n    salePrice {\\n      value\\n      currencyCode\\n    }\\n    retailPrice {\\n      value\\n      currencyCode\\n    }\\n  }\\n\\n  \\n  fragment multipleChoiceOption on MultipleChoiceOption {\\n    values {\\n      edges {\\n        node {\\n          label\\n          ...swatchOption\\n    
    }\\n      }\\n    }\\n  }\\n\\n  \\n  fragment swatchOption on SwatchOptionValue {\\n    isDefault\\n    hexColors\\n  }\\n\\n\\n\\n\\n","variables":{"first":6,"locale":"en-US","hasLocale":true,"featuredProducts":true}}',
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      freeSocketKeepAliveTimeout: 15000,
      timeout: 30000,
      socketActiveTTL: null,
      createSocketCount: 0,
      createSocketCountLastCheck: 0,
      createSocketErrorCount: 0,
      createSocketErrorCountLastCheck: 0,
      closeSocketCount: 0,
      closeSocketCountLastCheck: 0,
      errorSocketCount: 0,
      errorSocketCountLastCheck: 0,
      requestCount: 0,
      requestCountLastCheck: 0,
      timeoutSocketCount: 0,
      timeoutSocketCountLastCheck: 0,
      [Symbol(kCapture)]: false
    },
    redirect: 'manual',
    onRedirect: [Function]
  }
}
```
Is anyone here can help me to solve this problem? Thanks !!!

**Comment by bbeldame** [comment]
For more information I have this problem on my windows machine and not on my macbook.

**Comment by Itsaadarsh** [comment]
Hey, there @bbeldame did you use the proper `.env.local`  variables?

**Comment by blanklong28** [comment]
@Itsaadarsh  emm.. I haven't change the .env.template to .env.local.. And which value can  I assign them?

**Comment by Itsaadarsh** [comment]
Hey @blanklong28 tbh I'm also having the same doubt I'm unclear of the `.env.local` variables and their value. I thought you were past all of that so I thought I'd ask you.

**Comment by bbeldame** [comment]
I fixed my issue and it had nothing to do with macbook/windows. Only that when I copy pasted the .env that I wanted, it added some formatting (I copied from Notion). I didn't see that it changed the formatting so the error was just that the BIGCOMMERCE_STORE_API_URL and BIGCOMMERCE_STOREFRONT_API_URL were badly typed.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
