### ISSUE TITLE
development with localhost result in error

### ISSUE THREAD

**Issue by haegemonia76** [vercel/commerce#249]
Hello,
I'm currently developing a provider for Aquilacms and I have a weird behavior, I can't use localhost anymore when referencing my local Aquilacms development environment.

instead of `http://localhost:3010` I have to use `http://192.168.1.138:3010` or else it send me this error `queryA ENOTFOUND localhost`

Did someone change something that prevent localhost to be used ?

Full error message :
```
AquilacmsNetworkError: Fetch to Aquilacms failed: queryA ENOTFOUND localhost
    at Object.fetchStoreApi [as storeApiFetch] (C:\Users\haege\workspace\github\AquilaCMS\commerce\.next\server\pages\index.js:7102:11)
    at async getAllProducts (C:\Users\haege\workspace\github\AquilaCMS\commerce\.next\server\pages\index.js:8142:7)
    at async getStaticProps (C:\Users\haege\workspace\github\AquilaCMS\commerce\.next\server\pages\index.js:14017:7)
    at async renderToHTML (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\render.js:28:1737)
    at async C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:109:97
    at async __wrapper (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:134:387)
    at async DevServer.renderToHTML (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:135:522)
    at async DevServer.renderToHTML (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\server\next-dev-server.js:35:578)
    at async DevServer.render (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:72:236)
    at async Object.fn (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:47:704)
    at async Router.execute (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:66:1042)
    at async DevServer.handleRequest (C:\Users\haege\workspace\github\AquilaCMS\commerce\node_modules\next\dist\next-server\server\next-server.js:34:504)
```

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
