### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by mariusa** [vercel/commerce#262]
I've cloned the repo and followed steps 3-7 at
https://github.com/vercel/commerce#contribute

.env.local
```
# Available providers: bigcommerce, shopify
COMMERCE_PROVIDER=shopify

BIGCOMMERCE_STOREFRONT_API_URL=
BIGCOMMERCE_STOREFRONT_API_TOKEN=
BIGCOMMERCE_STORE_API_URL=
BIGCOMMERCE_STORE_API_TOKEN=
BIGCOMMERCE_STORE_API_CLIENT_ID=
BIGCOMMERCE_CHANNEL_ID=

NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=name.myshopify.com
NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=224...
```

but get this error:
```
$ yarn dev
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/marius/work/commerce/.env.local
next.config.js {
  "commerce": {
    "provider": "shopify",
    "features": {
      "wishlist": true,
      "customCheckout": false
    }
  },
  "images": {
    "domains": [
      "cdn.shopify.com"
    ]
  },
  "i18n": {
    "locales": [
      "en-US",
      "es"
    ],
    "defaultLocale": "en-US"
  },
  "env": {
    "COMMERCE_WISHLIST_ENABLED": true
  }
}
event - compiled successfully
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
TypeError: Cannot read property 'url' of undefined
    at ProductCard (webpack-internal:///./components/product/ProductCard/ProductCard.tsx:136:36)
    at processChild (/home/marius/work/commerce/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/marius/work/commerce/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/marius/work/commerce/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/marius/work/commerce/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/marius/work/commerce/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/marius/work/commerce/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/home/marius/work/commerce/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/marius/work/commerce/node_modules/next/dist/next-server/server/render.js:54:1142)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/marius/work/commerce/node_modules/next/dist/next-server/server/next-server.js:109:97
    at async __wrapper (/home/marius/work/commerce/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/home/marius/work/commerce/node_modules/next/dist/next-server/server/next-server.js:134:387)
    at async DevServer.renderToHTML (/home/marius/work/commerce/node_modules/next/dist/next-server/server/next-server.js:135:522)
```

Thanks

**Comment by cond0r** [comment]
@mariusa one of your products doesn't have an image

**Comment by mariusa** [comment]
Thanks for the fix! Looking forward to test it.

**Comment by mariusa** [comment]
Hi, `master` still doesn't work. There are no recent changes at
https://github.com/vercel/commerce/tree/master/components/product/ProductCard
(latest change: last month)

The commit says 'This commit does not belong to any branch on this repository.'
https://github.com/vercel/commerce/pull/264/commits/1dce23c91a33dc36d4891622069d9abb02b9dddb

Can't figure out why the fix didn't make it to the repo?

**Comment by mariusa** [comment]
@okbel Would you please see the comment above? Commit didn't make it.
