### ISSUE TITLE
In BigCommerce you can get the API tokens from the Store's control panel - you can refer to our documentation on authentication here: https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication

### ISSUE THREAD

**Issue by Crelloc** [vercel/commerce#287]
In BigCommerce you can get the API tokens from the Store's control panel - you can refer to our documentation on authentication here: https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication
You will also need a graphql auth token: https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken

The easiest way to connect however, is to use the Vercel CLI and pull your .env.local. This is part of the native integration ;)

_Originally posted by @RayeEThompson in https://github.com/vercel/commerce/issues/39#issuecomment-729646032_

**Comment by Crelloc** [comment]
I can setup this project without vercel and use the graphql token revealed in bigcommerce's graphql playground. The issue is that the graphql token that's revealed in bigcommerce's playground always changes. So i need to generate a token for production. And when I create my own api token with a longer expiration date ([https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken](https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken)), the project build fails when generating static paths. This is because the api token is restricted to a specific cors origin.

So my question is, how do I generate a bigcommerce api key that doesn't fail at build time, when the api key is restricted to a cors_origin?

**Below is my graphql error after running "npm run build":**

> nextjs-commerce@1.0.0 build /home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app
> next build

Loaded env from /home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/.env.local
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ...The pages "/shipping-returns/, /blog/, /contact-us/" do not include a locale, or the locale is not supported. When using i18n, web pages from
BigCommerce are expected to have a locale or they will be ignored.

Please update the pages to include the default locale or make the pages invisible by
unchecking the "Navigation Menu" option in the settings of each web page


> Build error occurred
Error: Authentication required
    at Object.fetchGraphqlApi [as fetch] (/home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/.next/server/pages/[...pages].js:6872:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async getAllProductPaths (/home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/.next/server/pages/product/[slug].js:1292:7)
    at async getStaticPaths (/home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/.next/server/pages/product/[slug].js:1353:7)
    at async buildStaticPaths (/home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/node_modules/next/dist/build/utils.js:16:80)
    at async /home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/node_modules/next/dist/build/utils.js:26:612
    at async /home/deploy/CLIENTS/SKETCHLAB/sketchlab-vercel-app/node_modules/next/dist/build/tracer.js:1:1450 {
  type: 'FetcherError',
  errors: [ { message: 'Authentication required' } ],
  status: 401

**Comment by Crelloc** [comment]
SOLVED the issue: When I created the api token, I had to use channel "1" for channel id instead of the channel I created for my application:

POST: https://api.bigcommerce.com/stores/j6qkr5mkdw/v3/storefront/api-token

request body:

{
  "channel_id": 1,
  "expires_at": 1935039600,
  "allowed_cors_origins": [
    ....
  ]
}
