### ISSUE TITLE
Not able to develop locally

### ISSUE THREAD

**Issue by MecBonjourno** [vercel/commerce#302]
I'm currently trying to make some minor changes in the code but every time i try to `yarn run` the console return me this error:

Note: i've haven't made any changes in the code lately and the code was working last week

I've already tried to `yarn upgrade` , `yarn cache clear`  and `yarn build` . Nothing changed and the build didn't passed through due to the same error

`
FetcherError: Authentication required
    at Object.fetchGraphqlApi [as fetch] (C:\Users\guilherme.zago\Documents\darkvapeshopgo\.next\server\pages\index.js:7533:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getAllProducts (C:\Users\guilherme.zago\Documents\darkvapeshopgo\.next\server\pages\index.js:8816:7)
    at async getStaticProps (C:\Users\guilherme.zago\Documents\darkvapeshopgo\.next\server\pages\index.js:15062:7)
    at async renderToHTML (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\render.js:28:1737)
    at async C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:109:97
    at async __wrapper (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:134:387)
    at async DevServer.renderToHTML (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:135:522)
    at async DevServer.renderToHTML (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\server\next-dev-server.js:35:578)
    at async DevServer.render (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:72:236)
    at async Object.fn (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:56:580)
    at async Router.execute (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:66:1042)
    at async DevServer.handleRequest (C:\Users\guilherme.zago\Documents\darkvapeshopgo\node_modules\next\dist\next-server\server\next-server.js:34:504) {
  code: undefined,
  errors: [ { message: 'Authentication required' } ],
  status: 401
}
`
![image](https://user-images.githubusercontent.com/34528662/117148972-23599700-ad8d-11eb-9fff-13506dbe249e.png)

Any ideas on how to get over it?

**Comment by Vandivier** [comment]
1. is your repo open? if i could clone ur code I could try to reproduce the error
2. have you tried running w `vercel dev` instead of the yarn way?
3. can you log into bigcommerce outside of your app? make sure the vercel link to bigcommerce is able to do the same (no outdated password in the vercel integration, etc.) you may need to pass reset on bigcommerce if u can't get in
