### ISSUE TITLE
yarn dev fails but npm install then npm run dev works

### ISSUE THREAD

**Issue by lack-of-gravitas** [vercel/commerce#553]
yarn dev fails when attempting to compile and run locally on a fresh clone of the repo.

Steps to Replicate
1 - git clone from repo
2 - rename .env.template > env.local
3 - update env variable to local
4 - yarn add -D cross-env (i am on windows)
5 - yarn install for remaining packages
6 - update 'dev' startup command and add 'cross-env ...' prefix
7 - yarn dev
8 - FAILED BUILD
9 - npm install
10 - npm run dev
11 - code compiles, localhost:3000 loads

```
$ yarn dev
yarn run v1.22.17
$ cross-env NODE_OPTIONS='--inspect' next dev
Debugger listening on ws://127.0.0.1:9229/f9fde3c4-8a99-488c-bf42-8ac2d80972eb
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\lack-of-gravitas\praxio\klubs\commerce\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
next.config.js {
  "commerce": {
    "features": {
      "cart": false,
      "search": false,
      "wishlist": false,
      "customerAuth": false,
      "customCheckout": false
    },
    "provider": "local"
  },
  "i18n": {
    "locales": [
      "en-US",
      "es"
    ],
    "defaultLocale": "en-US"
  },
  "images": {
    "domains": [
      "localhost"
    ]
  },
  "env": {}
}
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[2].use[1]de_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[2].use[2]!./compo/cart/CartItem/CartItem.module.css
C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\caniuse-lite\data\features\urlsearcms.js:1

SyntaxError: Invalid or unexpected token
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[2].use[1]de_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[2].use[2]!./compo/cart/CartItem/CartItem.module.css
C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\caniuse-lite\data\features\urlsearcms.js:1

SyntaxError: Invalid or unexpected token
Error: Cannot find module 'C:\Users\lack-of-gravitas\praxio\klubs\commerce\.next\server\pages-mat.json'
Require stack:
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\requs
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\loadonents.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\api-.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\nexter.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\server\next.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\server\lib\start-server
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\cli\next-dev.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modulxt\dist\build\webpack\require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at getPagePath (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-r\server\require.js:1:735)
    at requirePage (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-r\server\require.js:1:1397)
    at loadComponents (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\nerver\server\load-components.js:1:1289)
    at DevServer.findPageComponents (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modulet\dist\next-server\server\next-server.js:77:296)
    at DevServer.renderErrorToHTML (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\dist\next-server\server\next-server.js:139:209) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-serverver\\require.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-serverver\\load-components.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-serverver\\api-utils.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-serverver\\next-server.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\server\\nex,
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\server\\librt-server.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\cli\\next-d',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\bin\\next' 
  ]
Require stack:
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\s-marver\server\load-components.js
ext-server\server\next-server.js                                          ext-server\server\requ
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\s                  loaderver\next.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\server\lib\start-server.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\cli\next-dev.js
erver\next.js
erver\next.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\server\lib\start-server.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\cli\next-dev.js
- C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\build\webpack\require-hook.jss:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at getPagePath (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\require.js:1:735)
    at requirePage (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\require.js:1:1397)
    at loadComponents (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\load-components.js:1:12899)
    at DevServer.findPageComponents (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\next-serverr.js:77:296)
    at DevServer.renderErrorToHTML (C:\Users\lack-of-gravitas\praxio\klubs\commerce\node_modules\next\dist\next-server\server\next-server..js:139:209) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-server\\server\\require.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-server\\server\\load-components.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-server\\server\\api-utils.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\next-server\\server\\next-server.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\server\\next.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\Users\\lack-of-gravitas\\praxio\\klubs\\commerce\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

**Comment by lack-of-gravitas** [comment]
closing as no response from NextJS and code is different
