### ISSUE TITLE
Rendering initial Boilerplate on Local Machine fails

### ISSUE THREAD

**Issue by Jyolbriger** [vercel/commerce#557]
If I try to render this project on my local machine via "npm run dev" I get this error:
(Firefox 94.0.1)

```
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at r (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:14587)
    at C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:15783
    at OriginalSource.streamChunks (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:9452)
    at s.exports (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:26463)
    at ReplaceSource.streamChunks (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:14737)
    at s.exports (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:26463)
    at ConcatSource.streamChunks (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:6880)
    at s.exports (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:26463)
    at u (C:\Projects\jahns-shop\node_modules\next\dist\compiled\webpack-sources3\index.js:1:25814)
```

**Comment by Jyolbriger** [comment]
I reinstalled NodeJS and the Boilerplate - now it works
