### ISSUE TITLE
Not able to build prod version when provider is set to vendure.

### ISSUE THREAD

**Issue by jramer** [vercel/commerce#566]
**How to reproduce:**
1. Clone this repo
2. Create `.env.local` with:
```
COMMERCE_PROVIDER=vendure
NEXT_PUBLIC_VENDURE_SHOP_API_URL=http://localhost:3001/shop-api
NEXT_PUBLIC_VENDURE_LOCAL_URL=/vendure-shop-api
```
3. `yarn install`
4. `yarn dev`
5. `yarn build`

**Setup:**
macOS Monterey 12.0.1 (tried both on Intel and Apple Silicon)
yarn v1.22.17
node v16.13.0
npm 8.1.0

**Output:**
```
yarn build
yarn run v1.22.17
$ next build
info  - Loaded env from /Users/me/git/storefront/.env.local
next.config.js {
  "commerce": {
    "features": {
      "cart": true,
      "search": true,
      "wishlist": false,
      "customerAuth": false,
      "customCheckout": false
    },
    "provider": "vendure"
  },
  "i18n": {
    "locales": [
      "en-US",
      "es"
    ],
    "defaultLocale": "en-US"
  },
  "images": {
    "domains": [
      "localhost",
      "demo.vendure.io"
    ]
  },
  "env": {
    "COMMERCE_CART_ENABLED": true,
    "COMMERCE_SEARCH_ENABLED": true
  }
}
info  - Checking validity of types
error - ESLint: Error while loading rule 'jsx-a11y/alt-text': rule.create is not a function Occurred while linting /Users/me/git/storefront/pages/404.tsx
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data ..node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:819:17)
    at process.target.send (node:internal/child_process:719:19)
    at reportError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:71:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
info  - Collecting page data ..node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:819:17)
    at process.target.send (node:internal/child_process:719:19)
    at reportError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:71:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn  - Restarted collecting page data for /product/[slug] because it took more than 60 seconds
warn  - See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
info  - Collecting page data .node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:819:17)
    at process.target.send (node:internal/child_process:719:19)
    at reportError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:71:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
info  - Collecting page data ..node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:819:17)
    at process.target.send (node:internal/child_process:719:19)
    at reportError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/Users/me/git/storefront/node_modules/jest-worker/build/workers/processChild.js:71:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

> Build error occurred
Error: Collecting page data for /product/[slug] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
    at onRestart (/Users/me/git/storefront/node_modules/next/dist/build/index.js:482:31)
    at Worker.isPageStatic (/Users/me/git/storefront/node_modules/next/dist/lib/worker.js:49:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/me/git/storefront/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/me/git/storefront/node_modules/next/dist/build/index.js:545:48
    at async Span.traceAsyncFn (/Users/me/git/storefront/node_modules/next/dist/trace/trace.js:74:20)
    at async Promise.all (index 17)
    at async /Users/me/git/storefront/node_modules/next/dist/build/index.js:530:13
    at async Span.traceAsyncFn (/Users/me/git/storefront/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/me/git/storefront/node_modules/next/dist/build/index.js:506:127
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jramer** [comment]
Ok. Sorry my fault.
You of course need to have your backend api running...
Closing this.
