### ISSUE TITLE
Add to cart throwing 500 error

### ISSUE THREAD

**Issue by brightonmike** [vercel/commerce#682]
Just set up a new deploy - everything fine except add to cart, which throws a function error.

```
2022-02-14T17:26:18.526Z	f3136d01-4b70-45e4-9442-0c7918c1fbb3	ERROR	Error: Cannot find module 'immutability-helper'
Require stack:
- /var/task/site/.next/server/pages/api/cart.js
- /var/task/node_modules/next/dist/server/base-server.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.6333 (/var/task/site/.next/server/pages/api/cart.js:25:18)
    at __webpack_require__ (/var/task/site/.next/server/webpack-api-runtime.js:25:42)
    at Object.5360 (/var/task/site/.next/server/chunks/294.js:767:37)
    at __webpack_require__ (/var/task/site/.next/server/webpack-api-runtime.js:25:42)
    at Object.2411 (/var/task/site/.next/server/pages/api/cart.js:121:17)
    at __webpack_require__ (/var/task/site/.next/server/webpack-api-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/site/.next/server/pages/api/cart.js',
    '/var/task/node_modules/next/dist/server/base-server.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
RequestId: f3136d01-4b70-45e4-9442-0c7918c1fbb3 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by okbel** [comment]
Is this still happening?
