### ISSUE TITLE
App will not run `MODULE_NOT_FOUND` styled-jsx 

### ISSUE THREAD

**Issue by HeavenlyEntity** [vercel/commerce#693]
#### Description of Issue

When I try to run my instance locally every single time I get `Cannot find module 'styled-jsx'`. Why is this happening?

The Following Solutions I've Tried with no luck:
- Delete node_modules out of all folders where I could find it and deleted the `yarn.lock` then repeated install.
- Installed `styled-jsx` manually to version `5`.
- Recloned and ran yarn in a separate repo.

Not sure what is going on here. I am thinking it can't be referenced from the site folder which is why maybe.

**Actual Behavior**
- Ran `yarn dev` in `site` directory after installing deps and received an error stating `styled-jsx` is not found.

**Expected Behavior**
- Run `yarn dev` and instance of server compiles app successfully.

**Specs:**
- OS: Windows 10 21H2 64-bit
- Browser: Chrome (98.0.4758.102)

**Errors:**

```shell
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\____\Documents\GitHub\commerce\site\.env.local
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'styled-jsx'
Require stack:
- C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\server\render.js
- C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\server\next-server.js     
- C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\server\next.js
- C:\Users\____\Documents\GitHubcommerce\node_modules\next\dist\server\lib\start-server.js
- C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\cli\next-dev.js
- C:\Users\____\Documents\GitHub\fcommerce\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\build\webpack\require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\____\Documents\GitHub\commerce\node_modules\next\dist\server\render.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\____\\Documents\\GitHub\\commerce\\node_modules\\next\\dist\\server\\render.js',
    'C:\\Users\\____\\Documents\\GitHub\\commerce\\node_modules\\next\\dist\\server\\next-server.js',
    'C:\\Users\\____\\Documents\\GitHub\\commerce\\node_modules\\next\\dist\\server\\next.js',
    'C:\\Users\\____\\Documents\\GitHub\\commerce\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\Users\\____\\Documents\\GitHub\\commerce\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\Users\\____\\Documents\\GitHub\commerce\\node_modules\\next\\dist\\bin\\next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Fasunle** [comment]
Hello,

I want to work on this but I can I regenerate the error so I can debug it.

**Comment by HeavenlyEntity** [comment]
Hi @Fasunle so I linked this issue directly with the UI library `next-ui` as this causes this error to occur. After I removed it this error disappeared.
